apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: service-api
  template:
    metadata:
      labels:
        app: service-api
    spec:
      containers:
        - name: service-api
          image: karanbht/nagp-service-api_v3
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: secret
                  key: mongo-uri
