apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9rYXJhbmJoYXRpYTUwNzo0OGFJN09RYjJKcHJSV3BCQG5hZ3AtY2x1c3Rlci5la3lwMjloLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1OYWdwLWNsdXN0ZXI=
