apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: YWRtaW4=        # admin
  password: cGFzc3dvcmQ=    # password
  mongo-root-username: S2FyYW5iaGF0aWE1MDc= # base64 of 'mongouser'
  mongo-root-password: NDhhSTdPUWIySnByUldwQg== # base64 of 'password123'
  mongo-uri: bW9uZ29kYitzcnY6Ly9rYXJhbmJoYXRpYTUwNzo0OGFJN09RYjJKcHJSV3BCQG5hZ3AtY2x1c3Rlci5la3lwMjloLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1OYWdwLWNsdXN0ZXI= # base64 of 'mongodb+srv://karanbhati507:
